bGomla/Areas/it/Controllers/MonitorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bGomlaDB;

namespace bGomla.Areas.it.Controllers
{
    public class MonitorController : Controller
    {
        // GET: Monitor
        bGomlaDBEntities db = new bGomlaDBEntities();
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult OutByBranchLocation(int id)
        {
            return View(db.Branches.Find(id));
        }

        public ActionResult InByBranchLocation(int id)
        {
            return View(db.Branches.Find(id));
        }


        public ActionResult Publication(int id)
        {
            return View(db.Publications.Find(id));
        }
    }
}

bGomla/Controllers/API/BackupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using bGomlaDB;

namespace bGomla.Controllers.API
{
    public class BackupController : ApiController
    {
        bGomlaDBEntities db = new bGomlaDBEntities();
        [HttpGet]
        public IHttpActionResult Full() {
            CheckBackup(1, 2);
            return Ok("Full compelted");
        }
        [HttpGet]
        public IHttpActionResult Differential()
        {
            CheckBackup(2, 3);
            return Ok("Differential compelted");
        }
        [HttpGet]
        public IHttpActionResult Transaction()
        {
            CheckBackup(3, 5);
            return Ok("Transaction compelted");
        }

        private void CheckBackup(int backuptypeID, int TicketTypeID)
        {

            var allPlans = db.Backups.Where(x => x.BackupTypeID == backuptypeID).ToList();
            _app.Files files = new _app.Files();



            foreach (var p in allPlans)
            {
                if (p.dbServer.Online)
                {

                    foreach (var loc in p.BackupLocations)
                    {

                        var lastfile = files.FilesInFolder(loc.Root, p.BackupType.Extention).OrderByDescending(x => x.CreationTime).FirstOrDefault();
                        var t = db.Tickets.Where(x => x.MachineID == p.dbServerID && x.TicketTypeID
                        == TicketTypeID && x.StatusID != TicketStatus.Closed && x.BackupLocationID == loc.LocationID).FirstOrDefault();

                        if (lastfile != null)
                        {
                            if (lastfile.CreationTime.AddMinutes(p.MinuteInterval) >= DateTime.Now)
                            {

                                if (t != null)
                                {
                                    t.DateClosed = DateTime.Now;
                                    t.StatusID = TicketStatus.Closed;
                                    db.SaveChanges();
                                }
                            }
                            else
                            {
                                OpenTicket(t, TicketTypeID, loc);
                            }

                        }




                        else
                        {
                            OpenTicket(t, TicketTypeID, loc);

                            //if (t == null)
                            //{
                            //    t = new Ticket
                            //    {
                            //        Counter = 0,
                            //        DateOpen = DateTime.Now,
                            //        MachineID = p.dbServerID,
                            //        StatusID = TicketStatus.Underinvestegation,
                            //        TicketTypeID = TicketTypeID
                            //    };

                            //    db.Tickets.Add(t);
                            //}
                            //t.Counter += 1;
                            //var allwoed = db.TicketTypes.Find(TicketTypeID).AllowedCounter;
                            //if (t.Counter >= allwoed)
                            //{
                            //    t.StatusID = TicketStatus.Open;
                            //}
                            //db.SaveChanges();
                        }
                    }
                }

            }

        }

        private void OpenTicket(Ticket t, int TicketTypeID, BackupLocation location) {

            if (t == null)
            {
                t = new Ticket
                {
                    Counter = 0,
                    DateOpen = DateTime.Now,
                    MachineID = location.Backup.dbServerID,
                    StatusID = TicketStatus.Underinvestegation,
                    TicketTypeID = TicketTypeID,
                    BackupLocationID = location.LocationID

                };

                db.Tickets.Add(t);
            }
            t.Counter += 1;
            var allwoed = db.TicketTypes.Find(TicketTypeID).AllowedCounter;
            if (t.Counter >= allwoed)
            {
                t.StatusID = TicketStatus.Open;
            }
            db.SaveChanges();

        }
    }
}

bGomla/Controllers/API/NetworkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using bGomlaDB;

namespace bGomla.Controllers.API
{
    public class NetworkController : ApiController
    {

        bGomlaDBEntities db = new bGomlaDBEntities();

        [HttpGet]
        public IHttpActionResult Servers()
        {
           
            var sl = db.dbServers.ToArray();

            string s = "";




            foreach (var srv in sl)
            {

                var t = db.Tickets.FirstOrDefault(x => x.StatusID != TicketStatus.Closed && x.MachineID == srv.ServerID
                        && x.TicketTypeID == 1);
                for (int i = 0; i < 2; i++)
                {

                    System.Net.NetworkInformation.Ping p = new System.Net.NetworkInformation.Ping();

                    if (p.Send(srv.Machien.IP).Status == System.Net.NetworkInformation.IPStatus.Success) {

                        // close any open tickets
                        if (t != null) { t.DateClosed = DateTime.Now; t.StatusID = TicketStatus.Closed; db.SaveChanges();}
                        break;
                    };


                    if (i == 1)
                    {
                        // s += srv.Branch.Name + " is bad.   ";
                        // open or update server ticket
                        var allowd = db.TicketTypes.Find(1).AllowedCounter;
                        if (t == null) {
                            t = new Ticket { Counter = 0 , DateOpen = DateTime.Now , MachineID = srv.ServerID ,
                                StatusID = TicketStatus.Underinvestegation,
                                TicketTypeID = 1  };
                            db.Tickets.Add(t);

                        }
                        t.Counter += 1;
                        if (t.Counter >= allowd )
                        { t.StatusID = TicketStatus.Open;  }

                       
                         db.SaveChanges();
                        
                       
                    }
                }
                
            }

         
            return Ok(s);
        }

    }
}

bGomla/Controllers/API/PreformanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Diagnostics;
using bGomlaDB;
using System.Management;

namespace bGomla.Controllers.API
{
    public class PreformanceController : ApiController
    {

        bGomlaDBEntities db = new bGomlaDBEntities();
        [HttpGet]
        public IHttpActionResult Servers()
        {

           // Log = "in method";
            try
            {
                foreach (var srv in db.dbServers.ToList())
                {
                    if (srv.Online)
                    {
                       // Log = srv.Branch.Name + "is working";
                        PerformanceCounter cpuCounter = new PerformanceCounter("Processor", "% Processor Time", "_Total", srv.Machien.Name);
                        PerformanceCounter ramCounter = new PerformanceCounter("Memory", "Available Bytes", String.Empty, srv.Machien.Name);
                        cpuCounter.NextValue();
                        System.Threading.Thread.Sleep(1000);
                      //  Log = "loaded ram + cpu";

                        var flot1 = cpuCounter.NextValue();
                      //  Log = "loaded cpu";
                        var flot2 = ramCounter.NextValue();
                      //  Log = "loaded ram";
                        MachinePerformanceCounter pc = new MachinePerformanceCounter
                        {
                            CPU = cpuCounter.NextValue(),
                            Ram = ramCounter.NextValue(),
                            MachineID = srv.ServerID,
                            pcDate = DateTime.Now
                        };
                        //  Log = "added ram + cpu";
                        ManagementPath path = new ManagementPath()
                        {
                            NamespacePath = @"root\cimv2",
                            Server = srv.Machien.Name
                        };

                        //ManagementPath path = new ManagementPath();
                        //Log = "new path object created";
                        //path.NamespacePath = @"root\cimv2";//@"\\.\root\cimv2";
                        ////@"root\cimv2";
                        //Log = "added namespace";
                        //path.Server = srv.Machien.Name;
                        //Log = "added server name";
                        ManagementScope scope = new ManagementScope(path);
                       // Log = "added scope";
                        string condition = "DriveLetter = '" + srv.DriveLetter.ToUpper() + ":'";
                        string[] selectedProperties = new string[] { "FreeSpace", "Capacity" };
                        SelectQuery query = new SelectQuery("Win32_Volume", condition, selectedProperties);
                        long free = 0, Capacity = 0;
                       // Log = "got HD";
                        using (ManagementObjectSearcher searcher = new ManagementObjectSearcher(scope, query))
                        using (ManagementObjectCollection results = searcher.Get())
                        {
                            ManagementObject volume = results.Cast<ManagementObject>().FirstOrDefault();

                            if (volume != null)
                            {
                                ulong freeSpace = (ulong)volume.GetPropertyValue("FreeSpace");
                                ulong capacityTotal = (ulong)volume.GetPropertyValue("Capacity");
                                free = Convert.ToInt64(freeSpace);
                                Capacity = Convert.ToInt64(capacityTotal);
                                srv.DriveFreeSpace = free;
                                srv.DriveCapacity = Capacity;
                            }
                            _app.ADO aDO = new _app.ADO();
                            srv.DatabaseSize = aDO.DatabaseSize(srv);
                            db.MachinePerformanceCounters.Add(pc);
                            db.SaveChanges();
                           // Log = "saved";
                        }

                        if (srv.LocalBackupLocationsDiskSpace != null)
                        {

                            var local = srv.LocalBackupLocationsDiskSpace;
                            condition = "DriveLetter = '" + local.DriveLetter.ToUpper() + ":'";
                             selectedProperties = new string[] { "FreeSpace", "Capacity" };
                             query = new SelectQuery("Win32_Volume", condition, selectedProperties);
                            
                            // Log = "got HD";
                            using (ManagementObjectSearcher searcher = new ManagementObjectSearcher(scope, query))
                            using (ManagementObjectCollection results = searcher.Get())
                            {
                                ManagementObject volume = results.Cast<ManagementObject>().FirstOrDefault();

                                if (volume != null)
                                {
                                    ulong freeSpace = (ulong)volume.GetPropertyValue("FreeSpace");
                                    ulong capacityTotal = (ulong)volume.GetPropertyValue("Capacity");
                                    free = Convert.ToInt64(freeSpace);
                                    Capacity = Convert.ToInt64(capacityTotal);
                                    local.DriveFreeSpace = free;
                                    local.DriveCapacity = Capacity;
                                }
                                db.SaveChanges();
                                
                            }

                        }



                    }
                }

                return Ok();
            }
            catch (Exception e)
            {
                // return Ok(Log + "---" + e.Message);
                return InternalServerError(e);
              
            }

           

        }

        //private string _log = "";
        //private string Log { get { return _log; } set { _log += (Environment.NewLine + value); } }
    }
}

bGomla/Areas/it/Views/Shared/layouts/_TwoColumesPage.cshtml
@model _app.PagesModel.TwoCoulmsPage


@{ var d = _app.UI.TwoCoulmsPage(Model); }


<div class="col-md-6">
    @foreach (var item in d.List1)
    {
        
        @Html.Partial(Model.PartialPath, item)

    }
</div>

<div class="col-md-6">
    @foreach (var item in d.List2)
    {

        @Html.Partial(Model.PartialPath, item)

    }
</div>

bGomla/Areas/it/Views/Shared/layouts/_itLayout.cshtml
@{
    Layout = "~/Views/Shared/layouts/_MasterLayout.cshtml";

}

<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar-wrapper">
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <div class="page-sidebar navbar-collapse collapse">
            <!-- BEGIN SIDEBAR MENU -->
            <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
            <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
            <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
            <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
            <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
            <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
            <ul class="page-sidebar-menu page-sidebar-menu-closed" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                <li class="start active ">
                    <a href="/it/">
                        <i class="icon-home"></i>
                        <span class="title">Dashboard</span>
                    </a>
                </li>

                <li>
                    <a href="javascript:;">
                        <i class="fa fa-arrow-circle-o-up"></i>
                        <span class="title">Out Going Replication</span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        @foreach (var item in _app.UI.Branches())
                        {
                            <li>
                                <a href="@Url.Action("OutByBranchLocation" , "Monitor" , new { id = item.BranchID })">
                                    @item.Name (@item.dbServers.FirstOrDefault().ServerPublications.Count())
                                </a>
                            </li>
                        }
                    </ul>
                </li>

                <li>
                    <a href="javascript:;">
                        <i class="fa fa-arrow-circle-o-down"></i>
                        <span class="title">Incoming Replication</span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        @foreach (var item in _app.UI.Branches())
                        {
                            <li>
                                <a href="@Url.Action("InByBranchLocation" , "Monitor" , new { id = item.BranchID })">
                                    @item.Name (@item.dbServers.FirstOrDefault().Subscrtions.Count())
                                </a>
                            </li>
                        }
                    </ul>
                </li>

                @foreach (var pubCat in _app.UI.publicationCategories())
                {
                    <li>
                        <a href="javascript:;">
                            @Html.Raw(pubCat.Icon)
                            <span class="title">@pubCat.Name Replications</span>
                            <span class="arrow "></span>
                        </a>
                        <ul class="sub-menu">
                            @foreach (var item in pubCat.Publications.OrderBy(x => x.Name).ToList())
                            {
                                <li>
                                    <a href="@Url.Action("Publication" , "Monitor" , new { id = item.PubID })">
                                        @item.Name
                                        @if (item.CatID != 1)
                                        {<span>(@item.ServerPublications.Count)</span>}


                                    </a>
                                </li>
                            }
                        </ul>
                    </li>
                }

                <li>
                    <a href="javascript:;">
                        <i class="fa fa-code"></i>
                        <span class="title">Servers Backup</span>
                    </a>
                    <ul class="sub-menu">

                        <li>
                            <a href="@Url.Action("index" , "Backup")">
                                All Servers
                            </a>
                        </li>
                        @foreach (var item in _app.UI.dbServers())
                        {

                            <li>
                                <a href="@Url.Action("BranchServer" , "Backup", new { id = item.ServerID })">
                                    @item.Branch.Name
                                </a>
                            </li>

                        }

                    </ul>
                </li>

                <li>
                    <a href="javascript:;">
                        <i class="fa fa-file"></i>
                        <span class="title">Reports</span>
                    </a>
                    <ul class="sub-menu">

                        <li>
                            <a href="@Url.Action("index" , "Preformance")">
                                Servers Preformance
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("index" , "Network")">
                                Network
                            </a>
                        </li>

                    </ul>
                </li>

            </ul>

            <!-- END SIDEBAR MENU -->
        </div>
    </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN PAGE HEAD -->
            
            <!-- END PAGE HEAD -->
            <!-- BEGIN PAGE BREADCRUMB -->
            <ul class="page-breadcrumb breadcrumb hide">
                <li>
                    <a href="javascript:;">Home</a><i class="fa fa-circle"></i>
                </li>
                <li class="active">
                    Dashboard
                </li>
            </ul>
            <!-- END PAGE BREADCRUMB -->

            @RenderBody()

            <!-- END PAGE CONTENT INNER -->
        </div>
    </div>
    <!-- END CONTENT -->
</div>


<div class="page-footer">
    <div class="page-footer-inner">
        2014 © Metronic by keenthemes.
    </div>

</div>
<div class="scroll-to-top">
    <i class="icon-arrow-up"></i>
</div>


<div id="static" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
    <div class="modal-body">
        <p>
            Would you like to continue with some arbitrary task?
        </p>
    </div>
    <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn btn-default">Cancel</button>
        <button type="button" data-dismiss="modal" class="btn blue">Continue Task</button>
    </div>
</div>