bGomla/Areas/it/Controllers/TickesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bGomlaDB;
using Microsoft.Ajax.Utilities;

namespace bGomla.Areas.it.Controllers
{
    public class TickesController : Controller
    {
        // GET: Tickes
        bGomlaDBEntities db = new bGomlaDBEntities();
        public ActionResult Index(int id)
        {
            if (id == 1)
            {return RedirectToAction("index", "Network", null); }

            return View();
        }

        
        
    }
}

bGomla/Areas/it/Views/Shared/Notifications/_TicketsList.cshtml
@model _app.PagesModel.TicketNotificationList


@if (Model.Tickets.Count > 0)
{
    Model.TicketType = Model.Tickets.FirstOrDefault().TicketType;

<li class="dropdown dropdown-extended dropdown-inbox">
    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown"
      data-close-others="true" aria-expanded="false">
        <i class="@Model.icon"></i>
        <span class="badge badge-@Model.CssClassName">
            @Model.Tickets.Count
        </span>
    </a>
    <ul class="dropdown-menu">
        <li class="external">
            <h3>@Model.Tickets.Count @Model.TicketType.Name tickets pending</h3>
            <a href="@Url.Action("index", "Tickets", new { id = Model.TicketType.TypeID })">view all</a>
        </li>
        <li>
            <div class="slimScrollDiv" >
                <ul class="dropdown-menu-list scroller" data-handle-color="#637283" data-initialized="1">


                    @foreach (var item in Model.Tickets)
                    {
                        @*<li>
                            <a href="@Url.Action("Details", "Tickes", new { id = item.TicketID })">
                                <span class="time">
                                    <time class="timeago" datetime="@item.DateOpen">
                                        @item.DateOpen
                                    </time>
                                </span>
                                <span class="details">
                                    <span class="label label-sm label-icon label-@Model.CssClassName">
                                        <i class="@Model.icon"></i>
                                    </span>
                                    @item.Machien.Name @item.TicketType.Message !
                                </span>
                            </a>
                        </li>*@

                        <li>
                            <a href="@Url.Action("Details", "Tickes", new { id = item.TicketID })">
                                <span class="photo">
                                    <i class="@Model.icon"></i>
                                </span>
                                <span class="subject">
                                    <span class="from">
                                        @item.Machien.Name
                                    </span>
                                    <span class="time">
                                        <time class="timeago" datetime="@item.DateOpen">
                                            @item.DateOpen
                                        </time>
                                    </span>
                                </span>
                                <span class="message">
                                    @item.TicketType.Message
                                    @if(item.BackupLocationID != null)
                                    {
                                        <span > in </span> @item.BackupLocation.Name
                                    }
                                </span>
                            </a>
                        </li>



                    }

                </ul>
            </div>
        </li>
    </ul>
</li>
}